# Generated by Django 5.1.2 on 2024-11-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_alter_navigation_item_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigation',
            options={'verbose_name': 'navigation', 'verbose_name_plural': 'navigations'},
        ),
    ]
