# Generated by Django 5.1.2 on 2024-11-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_alter_navigation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='language',
            field=models.CharField(choices=[('en-US', 'English'), ('bg-BG', 'Bulgarian')], default='en', max_length=5),
        ),
    ]
