# Generated by Django 5.1.2 on 2024-11-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0007_alter_navigation_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
            },
        ),
        migrations.AlterUniqueTogether(
            name='navigation',
            unique_together={('url_external', 'url_internal', 'language')},
        ),
        migrations.AlterField(
            model_name='navigation',
            name='language',
            field=models.CharField(choices=[('en-US', 'English'), ('bg-BG', 'Bulgarian')], default='en', max_length=7, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='menu',
            field=models.ManyToManyField(to='navigation.menu'),
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='slug',
        ),
    ]
