# Generated by Django 5.1.2 on 2024-11-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0008_menu_alter_navigation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='menu',
            field=models.ManyToManyField(blank=True, to='navigation.menu'),
        ),
    ]
