# Generated by Django 5.1.2 on 2024-11-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0009_alter_menu_name_alter_menu_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='navigation', to='navigation.menu'),
        ),
    ]
