# Generated by Django 5.1.2 on 2024-11-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0012_navigation_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='navigation',
            name='parent_id',
            field=models.ManyToManyField(blank=True, related_name='children', to='navigation.navigation', verbose_name='parent ID'),
        ),
    ]
