# Generated by Django 5.1.2 on 2024-11-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0013_remove_navigation_parent_id_navigation_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='navigation',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(-1), related_name='children', to='navigation.navigation', verbose_name='parent ID'),
        ),
    ]
