# Generated by Django 5.1.2 on 2024-11-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0015_language'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='navigation',
            unique_together={('url_external', 'url_internal')},
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='language',
        ),
        migrations.AddField(
            model_name='navigation',
            name='language',
            field=models.ManyToManyField(blank=True, to='navigation.language', verbose_name='language'),
        ),
    ]
