# Generated by Django 5.1.2 on 2024-11-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0016_alter_navigation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='order'),
        ),
    ]
