# Generated by Django 5.1.2 on 2024-12-03 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('navigation', '0017_alter_navigation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='anonymous_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navigation',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navigation',
            name='permission_required',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.permission'),
        ),
    ]
