# Generated by Django 5.1.2 on 2024-12-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='images/articles/saint.jpg', null=True, upload_to=''),
        ),
    ]
