# Generated by Django 5.1.2 on 2024-12-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='images/articles/saint.webp', null=True, upload_to=''),
        ),
    ]
