# Generated by Django 5.1.2 on 2024-12-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='saint.webp', null=True, upload_to=''),
        ),
    ]
