# Generated by Django 5.1.2 on 2024-11-15 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=30)),
                ('section_style', models.CharField(default='marble', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('style', models.CharField(default='marble', max_length=20)),
                ('type', models.CharField(blank=True, choices=[], default='TXT', max_length=15)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styling.section')),
            ],
        ),
    ]
