# Generated by Django 5.1.2 on 2024-11-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0002_alter_setting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='type',
            field=models.CharField(blank=True, choices=[('TXT', 'Text'), ('COL', 'Colour'), ('INT', 'Integer')], default='TXT', max_length=15),
        ),
    ]
