# Generated by Django 5.1.2 on 2024-11-15 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0005_alter_setting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='styling.section'),
        ),
    ]
