# Generated by Django 5.1.2 on 2024-11-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0006_alter_setting_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
