# Generated by Django 5.1.2 on 2024-11-23 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0007_setting_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'option', 'verbose_name_plural': 'settings'},
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=30, verbose_name='section name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_style',
            field=models.CharField(default='marble', max_length=20, verbose_name='section style'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='styling.section', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='style',
            field=models.CharField(default='marble', max_length=20, verbose_name='style'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='type',
            field=models.CharField(blank=True, choices=[('TXT', 'Text'), ('COL', 'Colour'), ('INT', 'Integer'), ('URL', 'URL'), ('WV', 'Whole Value')], default='TXT', max_length=15, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='value'),
        ),
    ]
