# Generated by Django 5.1.2 on 2024-11-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0008_alter_section_options_alter_setting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='enabled'),
        ),
    ]
