# Generated by Django 5.1.2 on 2024-11-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0009_alter_setting_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='value'),
        ),
    ]
