# Generated by Django 5.1.2 on 2024-11-19 20:12

import django.db.models.deletion
import izpitnik.orth_calendar.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayOccurrences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calendar', models.CharField(blank=True, choices=[('JIG', 'Julian in gregorian'), ('J', 'Julian'), ('G', 'Gregorian')], default='JIG', max_length=5)),
                ('easter_distance', models.SmallIntegerField(blank=True, editable=False, null=True, validators=[izpitnik.orth_calendar.validators.RangeValidator(-365, 365)])),
                ('christmas_distance', models.SmallIntegerField(blank=True, editable=False, null=True, validators=[izpitnik.orth_calendar.validators.RangeValidator(1, 365)])),
                ('feast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orth_calendar.feast')),
                ('saint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orth_calendar.saint')),
            ],
        ),
        migrations.AddField(
            model_name='feast',
            name='saint',
            field=models.ManyToManyField(related_name='feasts', to='orth_calendar.saint'),
        ),
    ]
