# Generated by Django 5.1.2 on 2024-11-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orth_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayoccurrences',
            name='feast',
        ),
        migrations.RemoveField(
            model_name='holidayoccurrences',
            name='saint',
        ),
        migrations.AddField(
            model_name='holidayoccurrences',
            name='feast',
            field=models.ManyToManyField(blank=True, to='orth_calendar.feast'),
        ),
        migrations.AddField(
            model_name='holidayoccurrences',
            name='saint',
            field=models.ManyToManyField(blank=True, to='orth_calendar.saint'),
        ),
    ]
