# Generated by Django 5.1.2 on 2024-11-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orth_calendar', '0002_remove_holidayoccurrences_feast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayoccurrences',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='holidayoccurrences',
            name='feast',
            field=models.ManyToManyField(blank=True, default=None, related_name='occurences', to='orth_calendar.feast'),
        ),
        migrations.AlterField(
            model_name='holidayoccurrences',
            name='saint',
            field=models.ManyToManyField(blank=True, default=None, related_name='occurences', to='orth_calendar.saint'),
        ),
    ]
