# Generated by Django 5.1.2 on 2024-11-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orth_calendar', '0004_alter_feast_options_alter_holidayoccurrences_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feast',
            options={'verbose_name': 'feast', 'verbose_name_plural': 'feasts'},
        ),
        migrations.AlterModelOptions(
            name='saint',
            options={'verbose_name': 'saint', 'verbose_name_plural': 'saints'},
        ),
    ]
