# Generated by Django 5.1.2 on 2024-11-23 19:51

import izpitnik.orth_calendar.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orth_calendar', '0005_alter_feast_options_alter_saint_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feast',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='saint',
            field=models.ManyToManyField(related_name='feasts', to='orth_calendar.saint', verbose_name='saint'),
        ),
        migrations.AlterField(
            model_name='holidayoccurrences',
            name='calendar',
            field=models.CharField(blank=True, choices=[('JIG', 'Julian in gregorian'), ('J', 'Julian'), ('G', 'Gregorian')], default='JIG', max_length=5, verbose_name='calendar'),
        ),
        migrations.AlterField(
            model_name='holidayoccurrences',
            name='christmas_distance',
            field=models.SmallIntegerField(blank=True, editable=False, null=True, validators=[izpitnik.orth_calendar.validators.RangeValidator(1, 365)], verbose_name='christmas distance'),
        ),
        migrations.AlterField(
            model_name='holidayoccurrences',
            name='date',
            field=models.DateField(unique=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='holidayoccurrences',
            name='easter_distance',
            field=models.SmallIntegerField(blank=True, editable=False, null=True, validators=[izpitnik.orth_calendar.validators.RangeValidator(-365, 365)], verbose_name='easter distance'),
        ),
        migrations.AlterField(
            model_name='holidayoccurrences',
            name='feast',
            field=models.ManyToManyField(blank=True, default=None, related_name='occurences', to='orth_calendar.feast', verbose_name='feast'),
        ),
        migrations.AlterField(
            model_name='holidayoccurrences',
            name='saint',
            field=models.ManyToManyField(blank=True, default=None, related_name='occurences', to='orth_calendar.saint', verbose_name='saint'),
        ),
        migrations.AlterField(
            model_name='saint',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
    ]
