# Generated by Django 5.1.2 on 2024-11-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orth_calendar', '0006_alter_feast_name_alter_feast_saint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedHolidayOccurrences',
            fields=[
            ],
            options={
                'verbose_name': 'related holiday occurrence',
                'verbose_name_plural': 'related holiday occurrences',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orth_calendar.holidayoccurrences',),
        ),
        migrations.AlterField(
            model_name='feast',
            name='saint',
            field=models.ManyToManyField(blank=True, related_name='feasts', to='orth_calendar.saint', verbose_name='saint'),
        ),
    ]
