name: Deploy Rozhdestvennik

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_ADDRESS }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts 

      - name: Deploy to VPS
        run: |
          ssh -tt ${{secrets.VPS_SSH_USER}}@${{secrets.VPS_SSH_ADDRESS}} << 'EOF'
            cd ${{secrets.VPS_PROJECT_PATH}}
            git pull origin main
            docker-compose exec web python manage.py collectstatic --noinput
            docker-compose down
            docker-compose up -d --build
          EOF

      - name: Deployment Success
        if: success()
        run: echo "✅ Deployment completed successfully!"

      - name: Deployment Failed
        if: failure()
        run: echo "❌ Deployment failed!"
